version: '3.8'

services:
  # PostgreSQL Database cho development
  db:
    image: postgres:15-alpine
    container_name: hello-vps-local-db
    environment:
      POSTGRES_DB: hello_vps_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"  # Dùng port 5433 để tránh conflict với production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - hello-vps-network

  # NestJS App cho development với hot reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hello-vps-local-app
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=hello_vps_db
    ports:
      - "3000:3000"
    volumes:
      # Mount source code để có hot reload
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - hello-vps-network
    command: npm run start:dev

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: hello-vps-local-nginx
    ports:
      - "8080:80"  # Nginx sẽ chạy trên port 8080
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - hello-vps-network

networks:
  hello-vps-network:
    driver: bridge

volumes:
  postgres_data:
