version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hello-vps-local-db
    environment:
      POSTGRES_DB: hello_vps_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"  # Dùng port 5433 để tránh conflict với production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
